version: "3.7"

services:
  postgres:
    container_name: postgres
    image: postgres:11.1
    ports:
      - 5432:5432
    networks:
      - rails_network
    volumes:
      - rails_postgres_data:/data/db
    environment:
      - POSTGRES_USER=rails_docker
      - POSTGRES_PASSWORD=rails_docker_password
  rails_app:
    container_name: rails_app
    image: rails-app:1.0.5
    ports:
      - 3000:3000
    depends_on:
      - postgres
    environment:
      - POSTGRE_USERNAME=postgres
      - POSTGRE_HOST=postgres
      - RAILS_DOCKER_DATABASE_PASSWORD=rails_docker_password
      - NODE_ENV=production
      - RAILS_SERVE_STATIC_FILES=enabled
      - RAILS_LOG_TO_STDOUT=enabled
      - RAILS_ENV=production
      - RACK_ENV=production

    networks:
      - rails_network

networks:
  rails_network:
    name: rails_network

volumes:
  rails_postgres_data:
    name: rails_postgres_data
