apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rails
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/marthin/Research/rails-docker/data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rails
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-rails
  resources:
    requests:
      storage: 1Gi






