apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-rails
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /tmp/rails-pv

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rails
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: pv-rails
  resources:
    requests:
      storage: 1Gi






