apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  type: LoadBalancer
  selector:
    app: app-rails
    tier: app
  ports:
  - port: 80
    targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-rails
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-rails
      tier: app
  template:
    metadata:
      labels:
        app: app-rails
        tier: app
    spec:
      containers:
      - name: app-rails
        image: andymarthin/rails-app:1.0.3
        ports:
        - containerPort: 3000
        env:
        - name: "POSTGRE_USERNAME"
          value: "postgres"
        - name: "POSTGRE_HOST"
          value: "db-service"
        - name: "RAILS_DOCKER_DATABASE_PASSWORD"
          value: "rails_docker_password"
